[project]
name = "fastcond-benchmarks"
version = "0.1.0"
description = "Performance benchmarking and visualization tools for fastcond"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.8.0",
]

[tool.uv]
dev-dependencies = []
